# version: "3.8"

# services:
#   backend:
#     build: ./backend
#     container_name: terabox-backend
#     ports:
#       - "8000:8000"
#     env_file: .env
#     volumes:
#       - ./backend/downloads:/app/downloads

#   frontend:
#     build: ./frontend
#     container_name: terabox-frontend
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend


# version: "3.9"

# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     volumes:
#       - ./backend/app:/app/app

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:80"


services:
  backend:
    build: ./backend
    container_name: terabox-backend
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend/downloads:/app/downloads

  frontend:
    build: ./frontend
    container_name: terabox-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
